spring.application.name=service-b
server.port=9001

spring.security.oauth2.resourceserver.jwt.issuer-uri=${SERVICE_A_ISSUER:http://localhost:9000}
service-b.audience=${SERVICE_B_AUDIENCE:service-b}

management.endpoints.web.exposure.include=health,info

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
