create table if not exists app_users (
    id bigint generated by default as identity primary key,
    username varchar(100) not null unique,
    password_hash varchar(500) not null,
    enabled boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table if not exists app_user_scopes (
    user_id bigint not null,
    scope varchar(100) not null,
    constraint pk_app_user_scopes primary key (user_id, scope),
    constraint fk_app_user_scopes_user
        foreign key (user_id) references app_users (id)
            on delete cascade
);

create index if not exists ix_app_users_username on app_users (username);
