create table if not exists app_roles (
    id bigint generated by default as identity primary key,
    name varchar(100) not null unique,
    description varchar(255),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table if not exists app_scopes (
    id bigint generated by default as identity primary key,
    name varchar(100) not null unique,
    description varchar(255),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table if not exists app_role_scopes (
    role_id bigint not null,
    scope_id bigint not null,
    constraint pk_app_role_scopes primary key (role_id, scope_id),
    constraint fk_app_role_scopes_role
        foreign key (role_id) references app_roles (id)
            on delete cascade,
    constraint fk_app_role_scopes_scope
        foreign key (scope_id) references app_scopes (id)
            on delete cascade
);

create table if not exists app_user_roles (
    user_id bigint not null,
    role_id bigint not null,
    constraint pk_app_user_roles primary key (user_id, role_id),
    constraint fk_app_user_roles_user
        foreign key (user_id) references app_users (id)
            on delete cascade,
    constraint fk_app_user_roles_role
        foreign key (role_id) references app_roles (id)
            on delete cascade
);

create index if not exists ix_app_roles_name on app_roles (name);
create index if not exists ix_app_scopes_name on app_scopes (name);
