spring.application.name=service-a
server.port=9000

service-a.saml.idp-metadata-uri=${SERVICE_A_SAML_IDP_METADATA_URI:classpath:saml/idp-metadata.xml}

spring.security.saml2.relyingparty.registration.shared-idp.entity-id={baseUrl}/saml2/service-provider-metadata/{registrationId}
spring.security.saml2.relyingparty.registration.shared-idp.assertion-consumer-service.location={baseUrl}/login/saml2/sso/{registrationId}
spring.security.saml2.relyingparty.registration.shared-idp.assertingparty.metadata-uri=${service-a.saml.idp-metadata-uri}

management.endpoints.web.exposure.include=health,info

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
